# Fail after an infinite loop
set timeout 5



set test "Binary compiled"
spawn ./test_compiled.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}

set test "Valid set of return value of a function"
spawn ./test_function_return_valid.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}

set test "Function local variable declared"
spawn ./test_function_local_variable_declared.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}

set test "Function, local variable list"
spawn ./test_function_local_variable_list.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}

set test "If then else"
spawn ./test_if_then_else.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}

set test "While do"
spawn ./test_while_do.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}

set test "Simple expression"
spawn ./test_expression_simple.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}

set test "Complex expression"
spawn ./test_expression_complex.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}

set test "Complex expression 2"
spawn ./test_expression_complex2.sh
expect {
    -re "PASSED" { pass $test }
    default      { fail $test }
}
